### ISSUE TITLE
[FEAT] Modify Anniversary View 

### ISSUE THREAD

**Issue by pinkishincoloragain** [pinkishincoloragain/whoami2#15]
### **Feature**
Modify Anniversary View

### **What should be done**
- [x] Change color theme by adding color to colors.json
- [x] Change theme atoms
- [x] Apply Glassmorphism
- [x] Change header / description phrases by changing asset/data/anniversary.json
- [x] Apply [Pretendard font](https://github.com/orioncactus/pretendard) globally

### **Additional context**
Thank you for joining AnniversaryProject @chaejunlee.

Result will be like this:
[Figma Link](https://www.figma.com/file/XvYdMv2sSqAdAPwWtEyLze/Untitled?node-id=0%3A1&t=WttYKer0qgXsyCon-1)

![AnniversaryForm_new](https://user-images.githubusercontent.com/39547381/208281894-44f716e8-c733-44fd-9a2f-41f669a17d49.png)

**Comment by pinkishincoloragain** [comment]
Looks fuckin' good to me👍
<img width="445" alt="Screen Shot 2022-12-18 at 20 51 28" src="https://user-images.githubusercontent.com/39547381/208296804-68a35df4-4f1b-43ae-a518-7bd55d109625.png">

**Comment by pinkishincoloragain** [comment]
## Test on mobile phone
- Environment: Instagram web browser, Galaxy S20+

<img src="https://user-images.githubusercontent.com/39547381/208297889-dbcc3201-c025-47b9-89b4-7a0473635687.jpeg" width="320px"/>

## Discussion needed:
If user adds new element -> should new element appear on top? or at the bottom(Current behaviour)?
(current behaviour looks a little laggy since user have to check bottom side to find new element)
Which one do you think is better? @chaejunlee 

## Additional features needed:
- [x] MultiSelectForm button might be small in mobile environment - need to make it bigger
- [ ] TextAreaForm focus action needs to be changed
- [ ] TextAreaForm needs higher borderRadius according to design
- [ ] TextAreaForm needs to notify user whether it is empty or not by using phrase(use isEmpty props)

**Comment by chaejunlee** [comment]
> ## Discussion needed:
> 
> If user adds new element -> should new element appear on top? or at the bottom(Current behaviour)?
> 
> (current behaviour looks a little laggy since user have to check bottom side to find new element)
> 
> Which one do you think is better? @chaejunlee 
> 

@pinkishincoloragain 

Yup! I totally agree with you that the new element should be added at the top.

Or just go with the input field be placed at the bottom.

**Comment by pinkishincoloragain** [comment]
<img width="1046" alt="Screen Shot 2022-12-18 at 21 54 49" src="https://user-images.githubusercontent.com/39547381/208299538-af26858a-7929-4dd7-af73-85e67814427b.png">

> Or just go with the input field be placed at the bottom.

That one looks even better. I'm on your side. @chaejunlee

**Comment by chaejunlee** [comment]
## Discussion Needed

### How to add the "Anonymous" option of "Name or Nickname (이름 & 별명)

- I don't think that the provided design (grid) goes well with the flow

- Therefore, I went with the previous design (flex or stack)

- What do you think? @pinkishincoloragain 

### How should I go with TextAreaForm?

- I'm not so sure about what to do the active state. What're your thoughts?

- I'm not so sure about how to use isEmpty thing. Is there any reference?

**Comment by pinkishincoloragain** [comment]
> ### How to add the "Anonymous" option of "Name or Nickname (이름 & 별명)
>
> - I don't think that the provided design (grid) goes well with the flow
>
> - Therefore, I went with the previous design (flex or stack)
>
> - What do you think? @pinkishincoloragain 

That makes sense. I think this feature should be developed. 
@chaejunlee Can you make new issue? We will discuss..
- How to create anonymous input form
- How to create random anonymous user name
- How to store data form anonymous user
- ...

This will involve designer's opinion also.

> ### How should I go with TextAreaForm?
>
> - I'm not so sure about what to do the active state. What're your thoughts?

Sorry, I meant `:focus` selector. It currently enlarges the rounded borderBottom and this behaviour looks weird to me. Can you make another `:focus` event with fabulous CSS?

> - I'm not so sure about how to use isEmpty thing. Is there any reference?

`isEmpty` is the state I created in `AnniversaryForm` to check its children's forms.
This state will be passed to `TextAreaForm` and notify user with `SmallText` if the the form is empty.

You'll easily find it in `AnniversaryForm` and you can pass it to `TextAreaForm`

If there's any error within the logic - could you kindly fix it?

```js
export default function AnniversaryForm() {

  ...

  const [isEmpty, setIsEmpty] = React.useState({
    name: true,
    instagram: true,
    description: true,
  });

  const handleInputFormChange = e => {
    const { value, name } = e.target;
    setIsEmpty({
      ...isEmpty,
      [name]: value === "",
    });

    setResponse({
      ...response,
      [name]: value,
    });
  };

  const canSubmit = !Object.values(isEmpty).includes(true);

  return (
    <AnniversaryFormWrapper onSubmit={e => handleSubmit(e)}>

      ...
      <TextAreaForm
        title={anniversary.questions[3]}
        name='description'
        onChange={handleInputFormChange}
        placeholder={anniversary.placeholder.message}
      />

     ...
    </AnniversaryFormWrapper>
  );
}

```


```js

export default function TextAreaForm({ title, placeholder, name, onChange, isEmpty }) {
  return (
    <TextAreaFormWrapper>
       ... 
        <SmallText>{isEmpty ? TEXT_INPUT_CHECK.empty : TEXT_INPUT_CHECK.okay}</SmallText>
      ...
    </TextAreaFormWrapper>
  );
}

```
Here is the SmallText with `isEmpty` props from mother, which is `AnniversaryForm`
