### ISSUE TITLE
[FEAT] Remodel Landing page to modified design

### ISSUE THREAD

**Issue by pinkishincoloragain** [pinkishincoloragain/whoami2#19]
### **Feature**
Remodel Landing page to modified design

### **What should be done**
- [ ] Remodel Landing page
- [x] Create link button to let user navigate to '내가 받은 연하장'

### **Additional context**

![Frame 28](https://user-images.githubusercontent.com/39547381/208755476-c7f33c66-1a48-43e2-a445-d57d061228c7.png)

**Comment by chaejunlee** [comment]
### New Landing page design

<img width="305" alt="Screenshot 2022-12-23 at 23 32 39" src="https://user-images.githubusercontent.com/48273875/209352364-202b8f0b-3dd6-4968-8593-bd6e164d9cfa.png">

**Comment by chaejunlee** [comment]
Looking Awesome!!!
